name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dishachaudhari/docker_1:latest
    - name: push docker image to github
      run: docker login -u  dishachaudhari -p ${{ secrets.SHERUU }} && docker push dishachaudhari/docker_1:latest
